---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: '12.16'

platforms:
- name: centos-6.8
  driver_config:
    box: opscode-centos-6.5
- name: centos-7.0
  driver_config:
    box: opscode-centos-7.0
  attributes:
    ephemeral_lvm:
      filesystem: xfs
- name: centos-7.2
  driver_config:
    box: opscode-centos-7.2
  attributes:
    ephemeral_lvm:
      filesystem: xfs
- name: debian-7.2.0
  driver_config:
    box: opscode-debian-7.2.0
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
- name: ubuntu-14.04
  driver_config:
    box: opscode-ubuntu-14.04

suites:
# This test suite mimics the behavior of being in a cloud which supports block device mapping
# The loopback devices given in block_device_mapping_ephemeral<N> should be included in
# the test/cookbooks/fake cookbook's attributes so they get created while running
# the test. EC2 and openstack clouds follow this format.
#
- name: default
  run_list: ["recipe[fake]", "recipe[ephemeral_lvm]"]
  attributes:
    cloud:
      provider: vagrant
    vagrant:
      block_device_mapping_ephemeral0: loop0
      block_device_mapping_ephemeral1: loop1

# This test mimics the behavior of being in a google compute engine. The ephemeral disks
# are mapped to /dev/disk/by-id/google-ephemeral-disk-<N>. Loopback device matching the
# device index should be set in the test/cookbooks/fake cookbook's attributes
# so they get created. For example, the following attributes will require the creation of
# loopback devices "/dev/loop0" and "/dev/loop1"
#
- name: gce
  run_list: ["recipe[fake::gce]", "recipe[ephemeral_lvm]"]
  attributes:
    cloud:
      provider: gce
    gce:
      attached_disks:
        disks:
        - deviceName: boot
          index: 0
          mode: READ_WRITE
          type: EPHEMERAL
        - deviceName: ephemeral-disk-0
          index: 1
          mode: READ_WRITE
          type: EPHEMERAL
        - deviceName: ephemeral-disk-1
          index: 2
          mode: READ_WRITE
          type: EPHEMERAL
