AllCops:
  Exclude:
    - 'berks-cookbooks/**/*'
    - 'knife.rb'
Style/AccessorMethodName:
  Exclude:
    - 'Rakefile'
Metrics/BlockNesting:
  Exclude:
    - 'libraries/helper.rb'
Style/GuardClause:
  Exclude:
    - 'test/cookbooks/fake/recipes/gce.rb'
