language: ruby
rvm:
- 2.3.1
before_install:
- curl -L https://www.getchef.com/chef/install.sh | sudo bash -s -- -P chefdk -v 1.0.3
- gem install bundler -v 1.11.2
install:
  - chef exec bundle install --jobs=3 --retry=3
before_script: chef exec bundle exec rake setup_test_environment
script: chef exec bundle exec rake except_kitchen
notifications:
  slack:
    secure: SqcVb40KzZcnESU9VKcUWpEmrPUamdrgqfmBAfndtHkGP4Pg3sESgPbZdY3CFsHtzjXV6I9LU+1b9YU3IXcKTos/+Eky5QixBxGwS2lq7yMB+FWHbi4FLvf9KaYx3lMwMuBzEmnJxMhbE7VX6rQk/FayR+0Og7g/InQKRVMJlMc=
